# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [7]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0],
             [1],
             [1],
             [0]])
print (y)

[[0]
 [1]
 [1]
 [0]]


In [8]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1             #此w的維度為3*4,4為下一個節點的個數
# define syn1
syn1 = 2*np.random.random((4,1)) - 1               #此w的維度為4*1,1對應到output
iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
print (syn0)
print (syn1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [19]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    #l1_error = y - l1
    l2_error = y - l2
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l2_delta = l2_error * nonlin(l2,True) ##目前l2_error似乎是扮演learning rate的角色
    
    l1_error = l2_delta.dot(syn1.T)  # how much did each l1 value contribute to the l2 error (according to the weights)?
    
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)
     # syn1 update weights
    ##
    if iter%2000 ==0:
        print('Error=',str(np.mean(np.abs(l2_error))))
print("Output After Training:")
print(l1)
print("\n\nOutput After Training l2")
print(l2)

Error= 0.0027315064182105086
Error= 0.0026959780987967684
Error= 0.002661771188022468
Error= 0.0026288063411965728
Error= 0.0025970107025414767
Output After Training:
[[7.42599267e-01 1.12565578e-01 9.27776258e-01 9.97445252e-01]
 [1.59782100e-01 3.55857955e-04 1.63352300e-02 8.98819101e-01]
 [9.96882994e-01 8.99148652e-01 2.17871816e-02 8.46774590e-01]
 [9.54712871e-01 2.44106180e-02 2.87918829e-05 1.11694598e-01]]


Output After Training l2
[[0.00210387]
 [0.99736924]
 [0.9975831 ]
 [0.0031138 ]]


In [48]:
#http://www.pythonheidong.com/blog/article/99121/

ValueError: operands could not be broadcast together with shapes (4,1) (3,4) (4,1) 