# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [9]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''
a_slice_prev = np.random.randn(4,4,3)
W = np.random.randn(4,4,3)
b =np.random.randn(1,1,1)

Z=conv_single_step(a_slice_prev,W,b)

print(Z)

2.7198994302808597


In [10]:
print(a_slice_prev)

[[[ 1.17893565  0.46997871  0.33352201]
  [ 1.59682108  0.99527317 -0.23848402]
  [ 0.77136998 -0.52897555  0.68374128]
  [-0.04533539 -0.48016312 -0.18353892]]

 [[-0.00500383  0.74638675 -0.53563205]
  [ 0.35118725 -1.52204449  1.57799465]
  [-1.17786527  0.7133619   0.88933033]
  [ 0.19240244  0.04106583  0.89959012]]

 [[ 0.14542388  0.56704867  1.25745525]
  [-1.15947855 -0.93723416 -1.6543415 ]
  [-1.85390615  0.22080181  0.79732721]
  [-0.95886333 -0.50396656  1.05998597]]

 [[ 0.92375154 -0.73495987  0.20775718]
  [-0.73350541  0.29125267 -1.68256896]
  [ 0.01925194 -0.06590726  0.34002132]
  [-0.42768083 -1.56039106 -0.95596842]]]


In [11]:
print(W)

[[[ 2.06231485  0.36981424 -0.16373692]
  [-1.43792659 -1.16880087 -0.33177397]
  [ 0.28174412 -0.271031    1.0020941 ]
  [-0.65576403 -0.25074402 -0.70638473]]

 [[-2.3095804  -1.36094028 -0.34278103]
  [ 1.55267329 -0.46076079  0.01048778]
  [-0.46443593  0.55122272 -0.51900428]
  [ 1.26342257 -1.70222225  0.62717514]]

 [[ 1.20894747 -0.3734142   1.19868535]
  [-2.01712643 -0.28114203 -0.02327102]
  [-0.03982586  0.99700094 -0.31957565]
  [-0.03110571  1.48885858 -0.37352543]]

 [[ 0.45172525  0.81817722  1.69305646]
  [ 0.6118547   0.65518691 -0.19850208]
  [-0.35005887  0.1650921   0.22028617]
  [-0.48622108  2.59988512 -0.20685133]]]


In [12]:
print(b)

[[[0.88065599]]]
